name = "singbox-manager"
main = "src/index.js"
compatibility_date = "2026-03-25"
workers_dev = true

[vars]
RULES_REPO_BASE = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge"
DEFAULT_TEST_URL = "https://www.gstatic.com/generate_204"
CONFIG_CACHE_TTL = "300"
RULE_CACHE_TTL = "86400"
DEFAULT_RULE_UPDATE_INTERVAL = "1d"
